name: CI Pipeline

on:
  push:
    branches: main

jobs:
  test-action:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Run 'Hello world action'
      uses: ./.github/actions
      with:
        who-to-greet: 'Carlos'
